# Generated by Django 2.2.5 on 2019-09-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20190912_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200, unique=True)),
                ('question_no', models.IntegerField(default=1)),
                ('product_image', models.ImageField(upload_to='question_images')),
                ('question_answer', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
