# Generated by Django 2.2.5 on 2019-09-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
