# Generated by Django 2.2.5 on 2019-09-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_userinfo_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
