# Generated by Django 2.2.5 on 2019-09-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20190914_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_comments',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
