# Generated by Django 2.2.5 on 2019-09-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_question_image_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='college_name',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
