# Generated by Django 2.2.5 on 2019-09-20 03:55

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_userinfo_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='download_files'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_clickable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='entered_answers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=phone_field.models.PhoneField(default=0, max_length=31),
        ),
    ]
